### ISSUE TITLE
Framework Rebuild

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#148]
# Rebuilding Missions Framework
## Zeus Slots for Staff

PIDs are needed for every staff member.
- [x] Flop: 76561198010136834
- [x] Eogos: 76561198046396805
- [x] Kat: 76561198046530838
- [x] Woods: 76561198045278741
- [x] Aselia: 76561198057849297
- [ ] Brain:
- [ ] Tactical Lolicon:
- [x] Yin: 76561198134427486
## Tasks
- [x] Remove ALiVE Logistics
- [x] #145 
- [x] Possibly add a car and helicopter MHQ
- [x] Look at gear frameworks
- [x] Look at alternatively teleport to squad frameworks
- [x] Clean up Apex Objects
- [x] Ensure that OCAP framework remains
- [x] Fix difficulty settings
- [x] #149

**Comment by Eogos** [comment]
76561198046396805

**Comment by PallyWoods** [comment]
76561198045278741

**Comment by Yin-Yue** [comment]
76561198134427486

**Comment by SchwererKonigstiger** [comment]
Tactical Lolicon & Brain are not going to be included in this framework update.
