### ISSUE TITLE
CUPop ToDo

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#334]
## Description.ext
- [x] Add description.ext
  - [ ] Change ACRE values in description.ext
- [ ] Add a mission picture (check discord)
- [ ] Add mission description

## Areas to Work on
- [x] Dorida
- [x] Rodopoli
- [ ] Telos Science Station (?)
- [ ] AIA
- [x] Pyrgos
- [ ] Russian FOBs

## Kits & Radios
- [x] Set team-level radios to 343s
- [x] Set platoon-level radios to 152s
- [x] Give Section Commanders 117Fs
- [x] Build kits for all classes
- [x] Add supplies to BMPs & Mi-17

## Outside of OP
- [ ] Write an in-operational briefing
- [ ] Figure out a radio callsign for command (E.G. CROSSROADS)
- [ ] Determine & List streamers and recorders
  - [ ] Advertise Stream on Reddit/ArmA Discord/FB/Etc.

**Comment by Eogos** [comment]
description.ext already existed btw
