### ISSUE TITLE
TIW Todo 11/12

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#375]
- [x] Make SQL and Medics spawnpoints
- [x] Turn ALiVE ai handling back to server instead of Headless Clients
- [x] Turn off the zone clearing map graphic
