### ISSUE TITLE
Mods Todo

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#386]
Remove:
 - [x] Pook
 - [x] Foxhounds (After Template Update)
 - [x] CTAB
 - [x] BWA3
 - [x] Enhanced Fortifications
 - [x] UTS-15
 - [x] Ares (fix dependencies)
 - [x] ASR AI (in favour of custom mods - See DDCMOD taskings)

Add/Update
 - [ ] ACRE Dev
 - [ ] Other Mods
