### ISSUE TITLE
AW todo list

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#427]
- [x] Remove Freedom spawn
- [x] Move Air Commander over to Freedom
- [x] Make Air Commander's starting aircraft locked only for players
- [ ] Switch player combat support CAS over to vanilla helos
- [ ] Make Air Commander's starting aircraft have infinite fuel and ammo
