### ISSUE TITLE
WW2 Zeus missions todo

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#451]
- [x] Switch BLUFOR roles to Wehrmacht by default
- [x] Add Russian REDFOR roles mirroring BLUFOR roles
- [x] Add US GREENFOR roles mirroring BLUFOR roles
- [x] Switch Russian medical truck to REDFOR MHQ
- [x] Switch US medical truck to GREENFOR MHQ
- [x] Add HQ spawns for REDFOR and GREENFOR
