### ISSUE TITLE
Main OPs Zeus Maintenance

### ISSUE THREAD

**Issue by Eogos** [DeathDeliveryCorps/Operations#469]
- [x] Add ACE Arsenals to all maps as per #441 (DO NOT remove BIS Arsenal)
- [x] Remove ACE Settings from all Zeus mission description.ext files as per #437 
- [x] Import CBA settings into all Zeus missions
- [x] Remove defenses from the USS Freedom on all missions as per #440 
- [x] Create Zeus Missions for all reasonable CUP maps that don't already have a mission on them (so don't do maps on things like desert island)
- [x] Remove Ravage dependency from all Zeus maps
- [x] Add third Headless Client slot to all Zeus maps

**Comment by Eogos** [comment]
make sure to relabel the BIS arsenal as such

**Comment by Eogos** [comment]
added 6th task

**Comment by Eogos** [comment]
added 7th task

**Comment by Eogos** [comment]
unchecked task 1 (you know, since it didn't actually work). ALSO PUT IT ON A DIFFERENT, SMALLER OBJECT LIEK THE BOX WE USED TO USE FOR AN ARSENAL
