### ISSUE TITLE
Altis War Mission Main Reference Issue

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#96]
Altis War Reference Issue
- [x] Add A-164 to airfield #95
- [x] Add additional MH-6s #95 #90
- [x] Add Bobcat #91 
- [x] Add additional ALiVE Transport helos #92 
- [x] Fix respawns of currently placed units #92 #95
- [x] Fix THOR Artillery Battery not spawning #94
